### ISSUE TITLE
Solution will not compile in VS 2017/2019

### ISSUE THREAD

**Issue by GerardDR** [XeroAPI/XeroWebhooksReceiver#2]
When I unzip the project and load it in VS 2017 or VS 2019 all projects gets 'upgraded' ("Visual Studio needs to make non-functional changes to this project in order to enable the project to open in released versions of Visual Studio newer than Visual Studio 2010 SP1 without impacting project behavior.").

After that most of the dependencies have a yellow warning sign next to it. If I select 'Manage NuGet Packages for solution' I get the message "No projects supported by NuGet in this solution". If I do the same on a project I get "WebhooksDataContracts NuGet packages is invalid".  If I close and reopen the solution I can do a manage nuget packages. Then I select the first one "Microsoft.AspNetCore.MVC, tick all projects and click on Install. I get a heap of error messages such as "Detected package downgrade: NETStandard.Library from 1.6.1 to 1.6.0.".  Etc etc etc.

**Comment by MJMortimer** [comment]
Hey @GerardDR, I've just updated the solution to .NetCore 2.2 and can successfully compile and run a webhooks integration out of VS2017. Can you try again now and see if you're any more successful?

**Comment by GerardDR** [comment]
Thanks mate, I'll give it a go tomorrow at work and let you know. Appreciate that...

**Comment by MJMortimer** [comment]
How did you get on @GerardDR? Safe to close this issue now?

**Comment by GerardDR** [comment]
Yes absolutely worked a treat, thank you so much!
